/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cl.model.bd.Pedido;
import cl.model.bd.Productos;
import cl.model.bd.sp_insertaPedido;
import cl.model.bd.sp_muestrPedido;
import cl.model.dao.MesasDao;
import cl.model.dao.OrdenesDao;
import cl.model.dao.PedidoDao;
import cl.model.dao.ProductosDao;
import cl.model.dao.SP_muestraIngDao;
import cl.model.dao.sp_eliminaOrdenDao;
import cl.model.dao.sp_insertaPedidoDao;
import cl.model.dao.sp_muestraPedidoDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import misExcepciones.MisExcepciones;

/**
 *
 * @author Angel
 */
public class ActualizarOrd extends javax.swing.JFrame {
ProductosDao pdao=new ProductosDao();
MesasDao mdao=new MesasDao();
SP_muestraIngDao midao=new SP_muestraIngDao();
OrdenesDao oDao=new OrdenesDao();
    sp_eliminaOrdenDao edao=new sp_eliminaOrdenDao();
sp_muestraPedidoDao mpdao=new sp_muestraPedidoDao();
DefaultListModel modeloLista=new DefaultListModel();
    DefaultListModel modeloLista2=new DefaultListModel();
    DefaultListModel modeloLista3=new DefaultListModel();
    /**
     * Creates new form ActualizarOrd
     */
    public ActualizarOrd() {
        initComponents();
        setLocationRelativeTo(null);
        btnEliminar.setEnabled(false);
        panMostrar.setVisible(false);
        txtId2.setVisible(false);
        txtId.setVisible(false);
        txtCanAux.setVisible(false);
    try {
        listCatProducto();
    } catch (SQLException ex) {
        Logger.getLogger(ActualizarOrd.class.getName()).log(Level.SEVERE, null, ex);
    }
        panAgregar.setVisible(false);
    }
    public void listCatProducto() throws SQLException{
        ArrayList<Productos>listCat;
        try{
            listCat=pdao.listCategoria(0);
            DefaultComboBoxModel combo=(DefaultComboBoxModel)comboCat.getModel();
            for(Productos prod: listCat){
                combo.addElement(prod.getCategoria());
            }
            comboCat.setModel(combo);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void listNombreProd() throws SQLException{    
    ArrayList<Productos>listNom;
    comboNombre.removeAllItems();
        try{
            listNom=pdao.listNombre(comboCat.getSelectedItem().toString());
            DefaultComboBoxModel combo=(DefaultComboBoxModel)comboNombre.getModel();
            for(Productos prod: listNom){
                combo.addElement(prod.getCategoria());
                listIDProd();
            }
            comboNombre.setModel(combo);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void listIDProd() throws SQLException{    
    ArrayList<Productos>listID;
        try{
            listID=pdao.listId(comboNombre.getSelectedItem().toString());
            for(Productos prod: listID){
                txtId.setText(String.valueOf(prod.getIdProducto()));
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void listIDProd2() throws SQLException{    
    ArrayList<Productos>listID;
        try{
            listID=pdao.listId((String) tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 1));
            for(Productos prod: listID){
                txtId2.setText(String.valueOf(prod.getIdProducto()));
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void pedidos() throws SQLException{
    ArrayList<sp_muestrPedido> listPedido;
    try {
    listPedido =mpdao.consultaDatos(Integer.valueOf(txtOrden.getText()));
    DefaultTableModel table=(DefaultTableModel)tblPedidos.getModel();
    table.setRowCount(0);
    for(sp_muestrPedido mp: listPedido){
        table.addRow(new Object[]{mp.getCantidad(),mp.getNombre(),mp.getPrecioU(),mp.getPrecioT()});
    }
    tblPedidos.setModel(table);
    } catch (SQLException ex) {
        System.out.println(ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrden = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panMostrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboCantidad = new javax.swing.JComboBox<>();
        txtId2 = new javax.swing.JTextField();
        txtCanAux = new javax.swing.JTextField();
        panAgregar = new javax.swing.JPanel();
        comboCat = new javax.swing.JComboBox<>();
        comboNombre = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        spiCantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listId = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listResumenOrden = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCantidad = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(211, 202, 177));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosolo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 76, 84));
        jLabel2.setText("C E N T E N A R I O   R E S T A U R A N T");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 76, 84));
        jLabel3.setText("ACTUALIZAR ORDEN");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("NO. ORDEN:");

        txtOrden.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdenActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnBuscar.setText("B U S C A R");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panMostrar.setBackground(new java.awt.Color(211, 202, 177));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("PEDIDOS DE LA ORDEN");

        tblPedidos.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripción", "Precio unitario", "Precio total"
            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("AGREGAR PEDIDO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR PEDIDO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Cant. a eliminar");

        comboCantidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCantidadItemStateChanged(evt);
            }
        });

        panAgregar.setBackground(new java.awt.Color(211, 202, 177));

        comboCat.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        comboCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCatItemStateChanged(evt);
            }
        });

        comboNombre.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        comboNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNombreItemStateChanged(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        spiCantidad.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        spiCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, 99, 1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("CANTIDAD:");

        listId.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listId);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("ID:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Resumen de orden:");

        jScrollPane3.setViewportView(listResumenOrden);

        jScrollPane4.setViewportView(listCantidad);

        jLabel11.setText("Cant.");

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnRegistrar.setText("ACTUALIZAR ORDEN");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAgregarLayout = new javax.swing.GroupLayout(panAgregar);
        panAgregar.setLayout(panAgregarLayout);
        panAgregarLayout.setHorizontalGroup(
            panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarLayout.createSequentialGroup()
                .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panAgregarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spiCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panAgregarLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panAgregarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel11))
                            .addGroup(panAgregarLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panAgregarLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRegistrar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panAgregarLayout.setVerticalGroup(
            panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarLayout.createSequentialGroup()
                .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(spiCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panAgregarLayout.createSequentialGroup()
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(4, 4, 4)
                        .addGroup(panAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panMostrarLayout = new javax.swing.GroupLayout(panMostrar);
        panMostrar.setLayout(panMostrarLayout);
        panMostrarLayout.setHorizontalGroup(
            panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMostrarLayout.createSequentialGroup()
                        .addComponent(panAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panMostrarLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(92, 92, 92)
                        .addComponent(btnEliminar)
                        .addGroup(panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMostrarLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCanAux, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panMostrarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
            .addGroup(panMostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMostrarLayout.setVerticalGroup(
            panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnEliminar)
                    .addComponent(jLabel9)
                    .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCanAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(panMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int idMes=0,idOrd=0,idRes=0,idCant=0,idIng=0;
        sp_insertaPedidoDao ipd=new sp_insertaPedidoDao();
        idOrd=Integer.valueOf(txtOrden.getText());
        for(int i=0;i<listId.getModel().getSize();i++){
            idCant=Integer.valueOf(listCantidad.getModel().getElementAt(i).toString());
            idIng=Integer.valueOf(listId.getModel().getElementAt(i).toString());
            sp_insertaPedido ip=new sp_insertaPedido(idCant, idIng, idOrd);
            try {
                ipd.insertaPedido(ip);
                JOptionPane.showMessageDialog(rootPane, "Registrado correctamente");
            } catch (SQLException ex) {
                Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            if(spiCantidad.getValue().equals(0)){
                throw new MisExcepciones(21);
            }else{
                listId.setModel(modeloLista);
                listResumenOrden.setModel(modeloLista2);
                listCantidad.setModel(modeloLista3);
                modeloLista.addElement(txtId.getText());
                modeloLista2.addElement(comboNombre.getSelectedItem().toString());
                modeloLista3.addElement(spiCantidad.getValue().toString());
            }

        }catch(MisExcepciones e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No hay elementos en la lista");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNombreItemStateChanged
        try {
            listIDProd();
        } catch (SQLException ex) {
            Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
        }catch (java.lang.NullPointerException ex2) {
            txtId.setText("");
        }
    }//GEN-LAST:event_comboNombreItemStateChanged

    private void comboCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCatItemStateChanged
        try {
            listNombreProd();
        } catch (SQLException ex) {
            Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
        }catch (java.lang.NullPointerException ex2) {
            txtId.setText("");
        }
    }//GEN-LAST:event_comboCatItemStateChanged

    private void comboCantidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCantidadItemStateChanged
        try{
            int resta = comboCantidad.getModel().getSize()-Integer.valueOf(comboCantidad.getSelectedItem().toString());
            txtCanAux.setText(String.valueOf(resta));
        }catch(java.lang.NullPointerException ex){
            txtCanAux.setText("");
        }
    }//GEN-LAST:event_comboCantidadItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int idOrd=0,idCant=0,idIng=0;
        sp_insertaPedidoDao ipd=new sp_insertaPedidoDao();
        idOrd=Integer.valueOf(txtOrden.getText());
        idCant=Integer.valueOf(txtCanAux.getText());
        idIng=Integer.valueOf(txtId2.getText());
        sp_insertaPedido ip=new sp_insertaPedido(idCant, idIng, idOrd);
        /*int rfc;
        PersonaDao objetoDao=new PersonaDao();
        rfc=Integer.valueOf(txtRfc.getText());
        Persona per=new Persona(rfc,"","","");
        try{
            objetoDao.borraPersona(per);
        }catch(SQLException ex){
            System.out.println("Registro no borrado");
        }
        System.out.println("Registro borrado");*/
        try {
            int idOrden,idProducto;
            PedidoDao pdao=new PedidoDao();
            idOrden=Integer.valueOf(txtOrden.getText());
            idProducto=Integer.valueOf(txtId2.getText());
            Pedido p=new Pedido(idProducto,idOrden);
            pdao.borraPedido(p);
            if(Integer.valueOf(txtCanAux.getText())==0){
                JOptionPane.showMessageDialog(this, "Orden actualizada 1");
            }
            else{
                ipd.insertaPedido(ip);
                JOptionPane.showMessageDialog(this,"Orden actualizada 2");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarOrd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panAgregar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        try{
            int dato=Integer.valueOf((String) tblPedidos.getModel().getValueAt(tblPedidos.getSelectedRow(),0));
            comboCantidad.removeAllItems();
            //txtPrueba.setText(dato);
            for(int i=0;i<tblPedidos.getRowCount();i++){
                if(tblPedidos.isRowSelected(i)){
                    btnEliminar.setEnabled(true);
                }
            }
            for(int i=1;i<=dato;i++){
                comboCantidad.addItem(String.valueOf(i));
                //txtPrueba.setText(String.valueOf(comboCantidad.getModel().getSize()));
                // tabla1 :es el nombre de tu tabla
                //DefaultTableModel tm = (DefaultTableModel) tabla1.getModel();

                //aca capturo el primer dato de la celda seleccionada

            }
            int resta = comboCantidad.getModel().getSize()-Integer.valueOf(comboCantidad.getSelectedItem().toString());
            txtCanAux.setText(String.valueOf(resta));
            try {
                listIDProd2();
            } catch (SQLException ex) {
                Logger.getLogger(ActualizarOrd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }catch(java.lang.NullPointerException ex){
            txtCanAux.setText("");
        }
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            pedidos();
            panMostrar.setVisible(true);
            btnEliminar.setEnabled(false);
            comboCantidad.removeAllItems();
            txtCanAux.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarOrd.class.getName()).log(Level.SEVERE, null, ex);
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Introduce un numero de orden");
            panMostrar.setVisible(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarOrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarOrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarOrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarOrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarOrd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboCantidad;
    private javax.swing.JComboBox<String> comboCat;
    private javax.swing.JComboBox<String> comboNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listCantidad;
    private javax.swing.JList<String> listId;
    private javax.swing.JList<String> listResumenOrden;
    private javax.swing.JPanel panAgregar;
    private javax.swing.JPanel panMostrar;
    private javax.swing.JSpinner spiCantidad;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCanAux;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtOrden;
    // End of variables declaration//GEN-END:variables
}
