/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cl.model.bd.Ingredientes;
import cl.model.bd.Jornada;
import cl.model.dao.JornadaDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class ActualizarJornada extends javax.swing.JFrame {
JornadaDao jdao = new JornadaDao();
    /**
     * Creates new form ActualizarJornada
     */
    public ActualizarJornada() {
        initComponents();
        setLocationRelativeTo(this);
        txtIdEmpleado.setVisible(false);
         if(chkLunes.isSelected()){
            panLunes.setVisible(true);
        }else{
            panLunes.setVisible(false);
        }
        if(chkMartes.isSelected()){
            panMartes.setVisible(true);
        }else{
            panMartes.setVisible(false);
        }
        if(chkMiercoles.isSelected()){
            panMiercoles.setVisible(true);
        }else{
            panMiercoles.setVisible(false);
        }
        if(chkJueves.isSelected()){
            panJueves.setVisible(true);
        }else{
            panJueves.setVisible(false);
        }
         if(chkViernes.isSelected()){
            panViernes.setVisible(true);
        }else{
            panViernes.setVisible(false);
        }
        if(chkSabado.isSelected()){
            panSabado.setVisible(true);
        }else{
            panSabado.setVisible(false);
        }
         if(chkDomingo.isSelected()){
            panDomingo.setVisible(true);
        }else{
            panDomingo.setVisible(false);
        }
    }
public void jornada() throws SQLException{
    ArrayList<Jornada> listJor;
    try {
    listJor = jdao.consultaDatos(Integer.valueOf(txtIdEmpleado.getText()));
    for(Jornada jo: listJor){
       if(jo.getDia().equals("Lunes")){
           chkLunes.setSelected(true);
           txtHoraELunes.setText(jo.getHoraEntrada());
           txtHoraSLunes.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Martes")){
           chkMartes.setSelected(true);
           txtHoraEMartes.setText(jo.getHoraEntrada());
           txtHoraSMartes.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Miercoles")){
           chkMiercoles.setSelected(true);
           txtHoraEMier.setText(jo.getHoraEntrada());
           txtHoraSMier.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Jueves")){
           chkJueves.setSelected(true);
           txtHoraEJue.setText(jo.getHoraEntrada());
           txtHoraSJue.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Viernes")){
           chkViernes.setSelected(true);
           txtHoraEViernes.setText(jo.getHoraEntrada());
           txtHoraSVier.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Sabado")){
           chkSabado.setSelected(true);
           txtHoraESab.setText(jo.getHoraEntrada());
           txtHoraSSab.setText(jo.getHoraSalida());
       }else if(jo.getDia().equals("Domingo")){
           chkDomingo.setSelected(true);
           txtHoraEDom.setText(jo.getHoraEntrada());
           txtHoraSDom.setText(jo.getHoraSalida());
       }
    }
    } catch (SQLException ex) {
        System.out.println(ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkLunes = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chkMartes = new javax.swing.JCheckBox();
        panLunes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHoraELunes = new javax.swing.JFormattedTextField();
        txtHoraSLunes = new javax.swing.JFormattedTextField();
        panMartes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHoraEMartes = new javax.swing.JFormattedTextField();
        txtHoraSMartes = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        chkMiercoles = new javax.swing.JCheckBox();
        panMiercoles = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHoraEMier = new javax.swing.JFormattedTextField();
        txtHoraSMier = new javax.swing.JFormattedTextField();
        panJueves = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtHoraEJue = new javax.swing.JFormattedTextField();
        txtHoraSJue = new javax.swing.JFormattedTextField();
        chkJueves = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        panViernes = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHoraSVier = new javax.swing.JFormattedTextField();
        txtHoraEViernes = new javax.swing.JFormattedTextField();
        chkViernes = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        panSabado = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtHoraESab = new javax.swing.JFormattedTextField();
        txtHoraSSab = new javax.swing.JFormattedTextField();
        chkSabado = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        panDomingo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtHoraEDom = new javax.swing.JFormattedTextField();
        txtHoraSDom = new javax.swing.JFormattedTextField();
        chkDomingo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(211, 202, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("JORNADA LABORAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 210, 23));
        jPanel1.add(txtIDEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 848, 185, -1));

        jLabel2.setText("LUNES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        chkLunes.setBackground(new java.awt.Color(211, 202, 177));
        chkLunes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chkLunes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLunes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkLunes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkLunesStateChanged(evt);
            }
        });
        chkLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLunesActionPerformed(evt);
            }
        });
        jPanel1.add(chkLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel3.setText("MARTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        chkMartes.setBackground(new java.awt.Color(211, 202, 177));
        chkMartes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkMartes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkMartesItemStateChanged(evt);
            }
        });
        jPanel1.add(chkMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        panLunes.setBackground(new java.awt.Color(211, 202, 177));

        jLabel9.setText("Entrada:");

        jLabel10.setText("Salida:");

        try {
            txtHoraELunes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraELunes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSLunes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSLunes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panLunesLayout = new javax.swing.GroupLayout(panLunes);
        panLunes.setLayout(panLunesLayout);
        panLunesLayout.setHorizontalGroup(
            panLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLunesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(40, 40, 40))
            .addGroup(panLunesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoraELunes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panLunesLayout.setVerticalGroup(
            panLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLunesLayout.createSequentialGroup()
                .addGroup(panLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraELunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 300, -1));

        panMartes.setBackground(new java.awt.Color(211, 202, 177));

        jLabel13.setText("Entrada:");

        jLabel14.setText("Salida:");

        try {
            txtHoraEMartes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEMartes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSMartes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSMartes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panMartesLayout = new javax.swing.GroupLayout(panMartes);
        panMartes.setLayout(panMartesLayout);
        panMartesLayout.setHorizontalGroup(
            panMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMartesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(40, 40, 40))
            .addGroup(panMartesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoraEMartes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSMartes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panMartesLayout.setVerticalGroup(
            panMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMartesLayout.createSequentialGroup()
                .addGroup(panMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1.add(panMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 300, -1));

        jLabel4.setText("MIERCOLES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        chkMiercoles.setBackground(new java.awt.Color(211, 202, 177));
        chkMiercoles.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkMiercoles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkMiercolesItemStateChanged(evt);
            }
        });
        jPanel1.add(chkMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        panMiercoles.setBackground(new java.awt.Color(211, 202, 177));

        jLabel11.setText("Entrada:");

        jLabel12.setText("Salida:");

        try {
            txtHoraEMier.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEMier.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSMier.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSMier.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panMiercolesLayout = new javax.swing.GroupLayout(panMiercoles);
        panMiercoles.setLayout(panMiercolesLayout);
        panMiercolesLayout.setHorizontalGroup(
            panMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMiercolesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(40, 40, 40))
            .addGroup(panMiercolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoraEMier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSMier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panMiercolesLayout.setVerticalGroup(
            panMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMiercolesLayout.createSequentialGroup()
                .addGroup(panMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEMier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSMier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 300, -1));

        panJueves.setBackground(new java.awt.Color(211, 202, 177));

        jLabel15.setText("Entrada:");

        jLabel16.setText("Salida:");

        try {
            txtHoraEJue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEJue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSJue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSJue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panJuevesLayout = new javax.swing.GroupLayout(panJueves);
        panJueves.setLayout(panJuevesLayout);
        panJuevesLayout.setHorizontalGroup(
            panJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJuevesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(40, 40, 40))
            .addGroup(panJuevesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoraEJue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSJue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panJuevesLayout.setVerticalGroup(
            panJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJuevesLayout.createSequentialGroup()
                .addGroup(panJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEJue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSJue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        chkJueves.setBackground(new java.awt.Color(211, 202, 177));
        chkJueves.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkJueves.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkJuevesItemStateChanged(evt);
            }
        });
        jPanel1.add(chkJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel5.setText("JUEVES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        panViernes.setBackground(new java.awt.Color(211, 202, 177));

        jLabel17.setText("Entrada:");

        jLabel18.setText("Salida:");

        try {
            txtHoraSVier.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSVier.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraEViernes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEViernes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panViernesLayout = new javax.swing.GroupLayout(panViernes);
        panViernes.setLayout(panViernesLayout);
        panViernesLayout.setHorizontalGroup(
            panViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panViernesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(40, 40, 40))
            .addGroup(panViernesLayout.createSequentialGroup()
                .addComponent(txtHoraEViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSVier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panViernesLayout.setVerticalGroup(
            panViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panViernesLayout.createSequentialGroup()
                .addGroup(panViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraSVier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraEViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        chkViernes.setBackground(new java.awt.Color(211, 202, 177));
        chkViernes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkViernes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkViernesItemStateChanged(evt);
            }
        });
        jPanel1.add(chkViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel6.setText("VIERNES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        panSabado.setBackground(new java.awt.Color(211, 202, 177));

        jLabel19.setText("Entrada:");

        jLabel20.setText("Salida:");

        try {
            txtHoraESab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraESab.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSSab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSSab.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panSabadoLayout = new javax.swing.GroupLayout(panSabado);
        panSabado.setLayout(panSabadoLayout);
        panSabadoLayout.setHorizontalGroup(
            panSabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSabadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(40, 40, 40))
            .addGroup(panSabadoLayout.createSequentialGroup()
                .addComponent(txtHoraESab, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSSab, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panSabadoLayout.setVerticalGroup(
            panSabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSabadoLayout.createSequentialGroup()
                .addGroup(panSabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraESab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        chkSabado.setBackground(new java.awt.Color(211, 202, 177));
        chkSabado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkSabado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkSabadoItemStateChanged(evt);
            }
        });
        jPanel1.add(chkSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel7.setText("SÁBADO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        panDomingo.setBackground(new java.awt.Color(211, 202, 177));

        jLabel21.setText("Entrada:");

        jLabel22.setText("Salida:");

        try {
            txtHoraEDom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEDom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtHoraSDom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSDom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panDomingoLayout = new javax.swing.GroupLayout(panDomingo);
        panDomingo.setLayout(panDomingoLayout);
        panDomingoLayout.setHorizontalGroup(
            panDomingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDomingoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(40, 40, 40))
            .addGroup(panDomingoLayout.createSequentialGroup()
                .addComponent(txtHoraEDom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(txtHoraSDom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panDomingoLayout.setVerticalGroup(
            panDomingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDomingoLayout.createSequentialGroup()
                .addGroup(panDomingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDomingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(panDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 290, -1));

        chkDomingo.setBackground(new java.awt.Color(211, 202, 177));
        chkDomingo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkDomingo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDomingoItemStateChanged(evt);
            }
        });
        jPanel1.add(chkDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jLabel8.setText("DOMINGO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 40, -1));

        btnRegistrar.setText("ACTUALIZAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosolo.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 120));

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkLunesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkLunesStateChanged
        if(chkLunes.isSelected()){
            panLunes.setVisible(true);
        }else{
            panLunes.setVisible(false);
        }
    }//GEN-LAST:event_chkLunesStateChanged

    private void chkLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLunesActionPerformed

    private void chkMartesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMartesItemStateChanged
        if(chkMartes.isSelected()){
            panMartes.setVisible(true);
        }else{
            panMartes.setVisible(false);
        }
    }//GEN-LAST:event_chkMartesItemStateChanged

    private void chkMiercolesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMiercolesItemStateChanged
        if(chkMiercoles.isSelected()){
            panMiercoles.setVisible(true);
        }else{
            panMiercoles.setVisible(false);
        }
    }//GEN-LAST:event_chkMiercolesItemStateChanged

    private void chkJuevesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkJuevesItemStateChanged
        if(chkJueves.isSelected()){
            panJueves.setVisible(true);
        }else{
            panJueves.setVisible(false);
        }
    }//GEN-LAST:event_chkJuevesItemStateChanged

    private void chkViernesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkViernesItemStateChanged
        if(chkViernes.isSelected()){
            panViernes.setVisible(true);
        }else{
            panViernes.setVisible(false);
        }
    }//GEN-LAST:event_chkViernesItemStateChanged

    private void chkSabadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkSabadoItemStateChanged
        if(chkSabado.isSelected()){
            panSabado.setVisible(true);
        }else{
            panSabado.setVisible(false);
        }
    }//GEN-LAST:event_chkSabadoItemStateChanged

    private void chkDomingoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDomingoItemStateChanged
        if(chkDomingo.isSelected()){
            panDomingo.setVisible(true);
        }else{
            panDomingo.setVisible(false);
        }
    }//GEN-LAST:event_chkDomingoItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            int idEmpleado2;
            idEmpleado2=Integer.valueOf(txtIdEmpleado.getText());
            Jornada j=new Jornada(idEmpleado2);
            JornadaDao jdao2=new JornadaDao();
            jdao2.eliminaJornada(j);   
            String horaEntrada,horaSalida;
            int idEmpleado;
            if(chkLunes.isSelected()){
                horaEntrada=txtHoraELunes.getText();
                horaSalida=txtHoraSLunes.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Lunes",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkMartes.isSelected()){
                horaEntrada=txtHoraEMartes.getText();
                horaSalida=txtHoraSMartes.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Martes",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkMiercoles.isSelected()){
                horaEntrada=txtHoraEMier.getText();
                horaSalida=txtHoraSMier.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Miercoles",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkJueves.isSelected()){
                horaEntrada=txtHoraEJue.getText();
                horaSalida=txtHoraSJue.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Jueves",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkViernes.isSelected()){
                horaEntrada=txtHoraEViernes.getText();
                horaSalida=txtHoraSVier.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Viernes",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkSabado.isSelected()){
                horaEntrada=txtHoraESab.getText();
                horaSalida=txtHoraSSab.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Sabado",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }if(chkDomingo.isSelected()){
                horaEntrada=txtHoraEDom.getText();
                horaSalida=txtHoraSDom.getText();
                idEmpleado=Integer.valueOf(txtIdEmpleado.getText());
                Jornada jo=new Jornada("Domingo",horaEntrada,horaSalida,idEmpleado);
                JornadaDao jDao=new JornadaDao();
                jDao.insertaJornada(jo);
            }
            JOptionPane.showMessageDialog(null,"JORNADA ESTABLECIDA");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    try {
        jornada();
    } catch (SQLException ex) {
        Logger.getLogger(ActualizarJornada.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarJornada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkDomingo;
    private javax.swing.JCheckBox chkJueves;
    private javax.swing.JCheckBox chkLunes;
    private javax.swing.JCheckBox chkMartes;
    private javax.swing.JCheckBox chkMiercoles;
    private javax.swing.JCheckBox chkSabado;
    private javax.swing.JCheckBox chkViernes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panDomingo;
    private javax.swing.JPanel panJueves;
    private javax.swing.JPanel panLunes;
    private javax.swing.JPanel panMartes;
    private javax.swing.JPanel panMiercoles;
    private javax.swing.JPanel panSabado;
    private javax.swing.JPanel panViernes;
    private javax.swing.JFormattedTextField txtHoraEDom;
    private javax.swing.JFormattedTextField txtHoraEJue;
    private javax.swing.JFormattedTextField txtHoraELunes;
    private javax.swing.JFormattedTextField txtHoraEMartes;
    private javax.swing.JFormattedTextField txtHoraEMier;
    private javax.swing.JFormattedTextField txtHoraESab;
    private javax.swing.JFormattedTextField txtHoraEViernes;
    private javax.swing.JFormattedTextField txtHoraSDom;
    private javax.swing.JFormattedTextField txtHoraSJue;
    private javax.swing.JFormattedTextField txtHoraSLunes;
    private javax.swing.JFormattedTextField txtHoraSMartes;
    private javax.swing.JFormattedTextField txtHoraSMier;
    private javax.swing.JFormattedTextField txtHoraSSab;
    private javax.swing.JFormattedTextField txtHoraSVier;
    private javax.swing.JTextField txtIDEmp;
    public javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
