/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cl.model.bd.Ordenes;
import cl.model.bd.Productos;
import cl.model.bd.SP_muestraIng;
import cl.model.dao.MesasDao;
import cl.model.bd.Mesas;
import cl.model.bd.sp_insertaOrden;
import cl.model.bd.sp_insertaPedido;
import cl.model.dao.OrdenesDao;
import cl.model.dao.ProductosDao;
import cl.model.dao.SP_muestraIngDao;
import cl.model.dao.sp_insertaOrdenDao;
import cl.model.dao.sp_insertaPedidoDao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import misExcepciones.MisExcepciones;

public class Ordenar extends javax.swing.JFrame {
    ProductosDao pdao=new ProductosDao();
    MesasDao mdao=new MesasDao();
    SP_muestraIngDao midao=new SP_muestraIngDao();
    OrdenesDao oDao=new OrdenesDao();
    DefaultListModel modeloLista=new DefaultListModel();
    DefaultListModel modeloLista2=new DefaultListModel();
    DefaultListModel modeloLista3=new DefaultListModel();
    int idMesa = 0;

    public Ordenar() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        listCatProducto();
         noOrden();
         txtId.setVisible(false);
    }
    
    public Ordenar(int idMesa) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);;
        listCatProducto();
        noOrden();
        txtId.setVisible(false);
        this.idMesa = idMesa;
    }
    
public void listCatProducto() throws SQLException{
        ArrayList<Productos>listCat;
        try{
            listCat=pdao.listCategoria(0);
            DefaultComboBoxModel combo=(DefaultComboBoxModel)comboCat.getModel();
            for(Productos prod: listCat){
                combo.addElement(prod.getCategoria());
            }
            comboCat.setModel(combo);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void listNombreProd() throws SQLException{    
    ArrayList<Productos>listNom;
    comboNombre.removeAllItems();
        try{
            listNom=pdao.listNombre(comboCat.getSelectedItem().toString());
            DefaultComboBoxModel combo=(DefaultComboBoxModel)comboNombre.getModel();
            for(Productos prod: listNom){
                combo.addElement(prod.getCategoria());
                listIDProd();
            }
            comboNombre.setModel(combo);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
public void listIDProd() throws SQLException{    
    ArrayList<Productos>listID;
        try{
            listID=pdao.listId(comboNombre.getSelectedItem().toString());
            for(Productos prod: listID){
                txtId.setText(String.valueOf(prod.getIdProducto()));
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }


public void cantidadIng() throws SQLException{
    ArrayList<SP_muestraIng> listIngredientes;
    try {
    listIngredientes =midao.consultaDatos(Integer.valueOf(spiCantidad.getValue().toString()),Integer.valueOf(txtId.getText()));
    DefaultTableModel table=(DefaultTableModel)tblIngredientes.getModel();
    //table.setRowCount(0);
    for(SP_muestraIng mi: listIngredientes){
        table.addRow(new Object[]{mi.getIdIngrediente(),mi.getIngrediente(),mi.getExistencia(),mi.getCantidad(),mi.getCantxprod(),mi.getCantNecesaria(),mi.getIdProducto(),mi.getDescripion()});
    }
    tblIngredientes.setModel(table);
    } catch (SQLException ex) {
        System.out.println(ex);
    }
}
public void noOrden() throws SQLException{
    ArrayList<Ordenes> noOrden;
    try {
    noOrden =oDao.muestraId(0);
    //table.setRowCount(0);
    for(Ordenes or: noOrden){
        int sum1=or.getIdOrden();
        int suma=sum1+1;
        txtIdOrden.setText(String.valueOf(suma));
    }
    } catch (SQLException ex) {
        System.out.println(ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboNombre = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spiCantidad = new javax.swing.JSpinner();
        comboCat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboPara = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtIdOrden = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listId = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResumenOrden = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCantidad = new javax.swing.JList<>();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtPrueba = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(211, 202, 177));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(211, 202, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboNombre.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        comboNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNombreItemStateChanged(evt);
            }
        });
        jPanel1.add(comboNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 28));

        tblIngredientes.setBackground(new java.awt.Color(211, 202, 177));
        tblIngredientes.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ingrediente", "Ingrediente", "Existencia", "Cantidad", "Cantidad por producto", "Cantidad necesaria", "ID Producto", "Descripción"
            }
        ));
        jScrollPane4.setViewportView(tblIngredientes);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 680, 170));

        btnAgregar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 70));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 20));

        spiCantidad.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        spiCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, 99, 1));
        jPanel1.add(spiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 100, -1));

        comboCat.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        comboCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCatItemStateChanged(evt);
            }
        });
        jPanel1.add(comboCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Para:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        comboPara.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        comboPara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Comer aqui", "Llevar" }));
        comboPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParaActionPerformed(evt);
            }
        });
        jPanel1.add(comboPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 178, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setText("Número de orden: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        txtIdOrden.setEnabled(false);
        jPanel1.add(txtIdOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 180, -1));

        txtId.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosolo.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 130, 120));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 76, 84));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("C E N T E N A R I O    R E S T A U R A N T  ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 400, 60));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 76, 84));
        jLabel14.setText("INCLUIR ORDENES");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(211, 202, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 35, -1));

        listId.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listId);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Resumen de orden:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setText("Cant.");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jScrollPane1.setViewportView(listResumenOrden);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 180, -1));

        jScrollPane3.setViewportView(listCantidad);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 50, -1));

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR ORDEN ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));

        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR ");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 320, 250));
        jPanel1.add(txtPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 30, -1));

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCatItemStateChanged
    try {
        listNombreProd();
    } catch (SQLException ex) {
        Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_comboCatItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     try {   
        if(spiCantidad.getValue().equals(0)){
            throw new MisExcepciones(21);
        }else{
        listId.setModel(modeloLista);
        listResumenOrden.setModel(modeloLista2);
        listCantidad.setModel(modeloLista3);
        modeloLista.addElement(txtId.getText());
        modeloLista2.addElement(comboNombre.getSelectedItem().toString());
        modeloLista3.addElement(spiCantidad.getValue().toString());
    
        cantidadIng();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (MisExcepciones ex){
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void comboNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNombreItemStateChanged
    try {
        listIDProd();
            SpinnerNumberModel sp = new SpinnerNumberModel();
            sp.setMinimum(0);
            sp.setMaximum(new ProductosDao().maxProductos(Integer.valueOf(txtId.getText())));
            spiCantidad.setModel(sp);
    } catch (SQLException ex) {
        Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
    }catch (java.lang.NullPointerException ex2) {
        txtId.setText("");
    }
    }//GEN-LAST:event_comboNombreItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if(listCantidad.getModel().getSize()==0){
            throw new MisExcepciones(22);
        }else{
        int idMes=0,idOrd=0,idRes=0,idCant=0,idIng=0;
        sp_insertaOrdenDao iod=new sp_insertaOrdenDao();
        sp_insertaPedidoDao ipd=new sp_insertaPedidoDao();
        idOrd=Integer.valueOf(txtIdOrden.getText());
        if(comboPara.getSelectedItem().toString().equals("Comer aqui")){
            idMes = idMesa;
        }
        if(comboPara.getSelectedItem().toString().equals("Llevar")){
            idMes=0;
        }
        sp_insertaOrden io= new sp_insertaOrden(idOrd,idMes,idRes);
        
        iod.insertaOrden(io);
        for(int i=0;i<listId.getModel().getSize();i++){
            idCant=Integer.valueOf(listCantidad.getModel().getElementAt(i).toString());
            idIng=Integer.valueOf(listId.getModel().getElementAt(i).toString());
            sp_insertaPedido ip=new sp_insertaPedido(idCant, idIng, idOrd);
                ipd.insertaPedido(ip);
                            JOptionPane.showMessageDialog(rootPane, "Registrado correctamente");
        }
        txtPrueba.setText(String.valueOf(listId.getModel().getSize()));
            }
        }catch (SQLException ex) {
                Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
        }catch (MisExcepciones ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
DefaultListModel listModel = (DefaultListModel) listCantidad.getModel();
listModel.removeAllElements();
DefaultListModel listModel2 = (DefaultListModel) listId.getModel();
listModel2.removeAllElements();
DefaultListModel listModel3 = (DefaultListModel) listResumenOrden.getModel();
listModel3.removeAllElements();
 DefaultTableModel tb = (DefaultTableModel) tblIngredientes.getModel();
        int a = tblIngredientes.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void comboParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParaActionPerformed
        if(comboPara.getSelectedItem().toString().equals("Comer aqui")){
            ventanas.Mesas mesa = new ventanas.Mesas();
            mesa.setVisible(true);
        }
        if(comboPara.getSelectedItem().toString().equals("Llevar")){
            btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_comboParaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ordenar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Ordenar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboCat;
    private javax.swing.JComboBox<String> comboNombre;
    private javax.swing.JComboBox<String> comboPara;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listCantidad;
    private javax.swing.JList<String> listId;
    private javax.swing.JList<String> listResumenOrden;
    private javax.swing.JSpinner spiCantidad;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdOrden;
    private javax.swing.JTextField txtPrueba;
    // End of variables declaration//GEN-END:variables
}
